if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
'key' => 'group_6326c19214c28',
'title' => 'Employees',
'fields' => array(
array(
'key' => 'field_6326c1a91c379',
'label' => 'Employees',
'name' => 'employees',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'collapsed' => '',
'min' => 0,
'max' => 0,
'layout' => 'table',
'button_label' => '',
'sub_fields' => array(
  array(
    'key' => 'field_6326c1c31c37a',
    'label' => 'Name',
    'name' => 'name_co',
    'type' => 'text',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
  ),
  array(
    'key' => 'field_6326c1e61c37b',
    'label' => 'Image',
    'name' => 'image',
    'type' => 'image',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'array',
    'preview_size' => 'thumbnail',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
  array(
    'key' => 'field_6326c2171c37c',
    'label' => 'Title',
    'name' => 'title',
    'type' => 'text',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
  ),
  array(
    'key' => 'field_6326c2221c37d',
    'label' => 'Division Title',
    'name' => 'division_title',
    'type' => 'text',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
  ),
  array(
    'key' => 'field_6326c2381c37e',
    'label' => 'Division Logo',
    'name' => 'division_logo',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'array',
    'preview_size' => 'thumbnail',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
  array(
    'key' => 'field_6326c24d1c37f',
    'label' => 'Years',
    'name' => 'years',
    'type' => 'number',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'min' => '',
    'max' => '',
    'step' => '',
  ),
  array(
    'key' => 'field_6326c2ab1c380',
    'label' => 'Bio',
    'name' => 'bio',
    'type' => 'textarea',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'maxlength' => '',
    'rows' => '',
    'new_lines' => '',
  ),
),
),
),
'location' => array(
array(
array(
  'param' => 'page',
  'operator' => '==',
  'value' => '15',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
));

endif;		
